version: "3"
services:
  db:
    image: postgres:9.6.5-alpine
    env_file: .env
    ports:
      - "25432:5432"
  migration:
    build: .
    env_file: .env
    command: "dotnet Hapthorn.dll migrate"
    depends_on:
      - db
  app:
    build: .
    env_file: .env
    ports:
      - "5000:5000"
    depends_on:
      - db
      - migration
