version: "3"
services:
  db:
    image: postgres:9.6.5-alpine
    env_file: .env
    ports:
      - "25432:5432"
  app:
    build: .
    env_file: .env
    ports:
      - "5000:5000"
    depends_on:
      - db
