version: "2"
services:
  db:
    image: postgres:9.6.5-alpine
    env_file: .env
    volumes:
      - ./docker_data/pgdata:/var/lib/postgresql/data
    ports:
      - "25432:5432"
  app:
    build: .
    env_file: .env
    ports:
      - "31867:5000"
    depends_on:
      - db
